### PR TITLE
FIX: pytmc api change + missing tmc file fix

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Fix for pytmc api change in v2.14.0 relating to listing records in PLCs
   * I noticed the last two pytmc versions were missing on PyPI this morning, so I uploaded them
* Fix for the epics docs template when no tmc file is available for a PLC
* Tweak of `.flake8` to allow reasonable/flexible long lines
   * Adjusted some unrelated sphinx config files to pass the flake8 config

## Context

For better or worse, our CI uses ads-deploy master. So, when this is merged, it should immediately fix the noted issues.

## Testing?

This was tested with a local copy of lcls-plc-kfe-vac, which was failing on Travis CI when generating docs: https://app.travis-ci.com/github/pcdshub/lcls-plc-kfe-vac/jobs/579127203

```
$ ipy ads-deploy docs ../plc/*.sln
+ ipython -i --pdb /Users/klauer/mc/envs/pytmc/bin/ads-deploy -- docs ../plc/plc-kfe-vac.sln
Python 3.7.5 (default, Oct 25 2019, 10:52:18)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.1 -- An enhanced Interactive Python. Type '?' for help.
Unable to import HappiPlugin
INFO:ads_deploy.docs:Rendering general template: index.rst -> index.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_summary.rst -> plc-kfe-vac_plc_kfe_vac_summary.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_summary.rst -> plc-kfe-vac_plc_kfe_vac_sim_summary.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_epics.rst -> plc-kfe-vac_plc_kfe_vac_epics.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_epics.rst -> plc-kfe-vac_plc_kfe_vac_sim_epics.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_nc.rst -> plc-kfe-vac_nc.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_boxes.rst -> plc-kfe-vac_boxes.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_pragmas.rst -> plc-kfe-vac_pragmas.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_source.rst -> plc-kfe-vac_plc_kfe_vac_source.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_source.rst -> plc-kfe-vac_plc_kfe_vac_sim_source.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_links.rst -> plc-kfe-vac_links.rst
INFO:ads_deploy.docs:Done
```

### CODE REVIEW

**Comment by ZLLentz** [comment]
CI failure is pre-commit minor formatting (newline EOF, whitespace, isort)

**Comment by ZLLentz** [comment]
> Fix for pytmc api change in v1.14.0

I'm assuming this was supposed to be v2.14.0 (latest)

**Comment by klauer** [comment]
> I'm assuming this was supposed to be v2.14.0 (latest)

I always ignore the major version when it's not zero, and then mess it up 🤷
You have it right

**Review by ZLLentz — APPROVED** [review]
Referred back to the pytmc source to make sure everything looked :+1:
Local testing should be sufficient for a docs build fix

**Comment by klauer** [comment]
Double-checking is much appreciated!  

pre-commit still wasn't happy after a `pre-commit run --all-files`, oddly enough, so I ran autoupdate and `run --all-files` again. If CI is good after that, I'll merge.

**Review by tangkong — APPROVED** [review]
Looks good to me as well 👍

**Pull request merged**
